### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by janicduplessis** [spencercarli/node-ddp-client#2]
Could you publish this to NPM? As far as I know it's the only DDP client that works with react-native.

**Comment by spencercarli** [comment]
@janicduplessis I've thought about that but honestly this is just a short term solution. I think there are better ways to handle ddp than what this package is doing. Have you seen [`react-native-meteor`](https://www.npmjs.com/package/react-native-meteor) or [Asteroid](https://github.com/mondora/asteroid)? I'm planning to migrate my apps over to `react-native-meteor`... is there any reason why you wouldn't want the features of that package vs this one?

I may still do so, just want to make sure there is a good reason to publish and maintain this

**Comment by spencercarli** [comment]
Done https://www.npmjs.com/package/node-ddp-client

**Comment by janicduplessis** [comment]
Thanks @spencercarli, sorry I forgot to come back to you on this one, I might check out the other ddp clients but I liked the simplicity of this one :)
