### ISSUE TITLE
how to preserve server side userId (this.userId) between crashes?

### ISSUE THREAD

**Issue by faceyspacey** [spencercarli/node-ddp-client#3]
Currently, I do `loginWithToken` on pure reloads, and I guess I can programmatically do that again on various crashes and hot module replacements that stop the web socket connection, but I was wondering what the underlying mechanism for communicating the userId to the server is. I looked through the code and saw the token isn't cached anywhere. So it must initially log the user in and then keep the websocket connection open, remembering the userId on the server until the websocket connection closes. But what if it was the fallback long polling way used by some browsers, etc? They must continue to pass the user ID from the client.

What do you think is the best way to keep the user consistently logged in while developing? Anything better than just littering the codebase with developer-only mechanisms to re-log the user in?

ps. I think I may have the automatically logging the user in with the token thing down--and the issue is when you update the server side code, the server drops the connection and requires you to start over, which is more difficult to coordinate a fix for on the client.

**Comment by spencercarli** [comment]
The goal of this package is to be pretty bare bones and not have anything react native specific - it's simply a clone of [`ddp-client`](https://github.com/hharnisc/node-ddp-client) since it's no longer maintained and need a bug fix.

The way I was keeping the user logged in in react native (before starting to use `react-native-meteor`) while developing is to store the user id in asyncstorage and attempt a login on app mount or reestablishment of a ddp connection.

To relogin after a server disconnect you could probably put a call to login inside of the ddpClient.call callback... hope this helps!

**Comment by faceyspacey** [comment]
Yea, that's what I'm gonna have to do, but it can't be the approach the Meteor browser client is using. They must detect a disconnect and remake the connection _and then also_ log the user in again with their token. Either that, or there's something glaring missing that allows the browser client to be remembered by the server when it comes back on. This is a big issue that any production app will need a solution for beyond just unnecessarily re-making requests. 

Also, not knowing whether this is just a development issue or if it also exists in production is quite scary. Are you using this or something else for your react native app?

**Comment by faceyspacey** [comment]
here's a little forum topic I started on it:

https://forums.meteor.com/t/react-native-app-logs-user-out-when-server-goes-down-i-e-during-development/22931

...the solution the browser client uses may simply be to use their equivalent of `_recoverNetworkError` to not just re-make the DDP connection, but also to login you with your token if it exists. In production that sounds dangerous though--because then you have a potentially large number of clients all reconnecting at the same time.

**Comment by spencercarli** [comment]
I'm using [`react-native-meteor`](https://github.com/inProgress-team/react-native-meteor) now.

**Comment by spencercarli** [comment]
Closing this as I'm no longer maintaining this repo.
